#!/usr/bin/env bash
# Idempotent Cloud Agent install script for the portfolio app.
# Prepares durable state: system packages, local PostgreSQL, node_modules,
# the local .env file, database schema (migrations) and seed data.
set -euo pipefail

cd "$(dirname "$0")/.."

PG_VERSION=16
PG_USER=portfolio
PG_PASSWORD=portfolio
PG_DB=portfolio
PG_SHADOW_DB=portfolio_shadow

echo "==> Ensuring PostgreSQL ${PG_VERSION} is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

echo "==> Starting PostgreSQL cluster (needed to provision role/databases)"
sudo pg_ctlcluster "${PG_VERSION}" main start 2>/dev/null || true
# Wait for the socket to accept connections.
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done

echo "==> Provisioning database role and databases (idempotent)"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${PG_USER}') THEN
    CREATE ROLE ${PG_USER} LOGIN PASSWORD '${PG_PASSWORD}' CREATEDB;
  END IF;
END
\$\$;
SELECT 'CREATE DATABASE ${PG_DB} OWNER ${PG_USER}'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${PG_DB}')\gexec
SELECT 'CREATE DATABASE ${PG_SHADOW_DB} OWNER ${PG_USER}'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${PG_SHADOW_DB}')\gexec
SQL

echo "==> Writing .env for local development (only if missing)"
if [ ! -f .env ]; then
  SECRET="$(openssl rand -hex 32)"
  cat > .env <<ENV
# Local development environment (generated by .cursor/install.sh)
DATABASE_URL="postgresql://${PG_USER}:${PG_PASSWORD}@localhost:5432/${PG_DB}?schema=public"
SHADOW_DATABASE_URL="postgresql://${PG_USER}:${PG_PASSWORD}@localhost:5432/${PG_SHADOW_DB}?schema=public"

# NextAuth / admin session
AUTH_SECRET="${SECRET}"
ADMIN_SESSION_SECRET="${SECRET}"

# Seed / bootstrap admin credentials (local only)
ADMIN_EMAIL="admin@example.com"
ADMIN_PASSWORD="ChangeMe12345"
ADMIN_NAME="Primary Admin"
ENV
fi

echo "==> Installing Node dependencies (npm ci)"
npm ci

echo "==> Applying Prisma migrations"
npx prisma migrate deploy

echo "==> Seeding the database"
npm run seed

echo "==> Install complete"
